#!/usr/bin/python

"""
Simple plot viewer for my own accumulated data.
"""

import itertools
import pathlib
import json
from array import array
from sys import argv
from typing import Tuple

from matplotlib import pyplot
from matplotlib.font_manager import FontProperties


abs_dir = pathlib.Path(__file__).absolute().parent
font = FontProperties(fname=abs_dir.joinpath("Font/NotoSansMonoCJKkr-Regular.otf"))


def viewer_fluctuation_data(total_view, concurrent_view) -> Tuple[array, array]:
    """
    Calculate possible viewer gain/lose from fluctuation of total view and live-viewers.

    :param total_view: Any sequence containing total views over time.
    :param concurrent_view: Any sequence containing live viewers over time.
    :return: int array for each approximate gain/lose of live viewers.
    """

    def view_diff_gen(source):
        yield 0

        iterator = zip(source, itertools.islice(source, 1, None))

        for previous, current in iterator:
            yield current - previous

    total_diff = array("i", view_diff_gen(total_view))
    live_diff_gen = array("i", view_diff_gen(concurrent_view))

    return total_diff, live_diff_gen


def plot_main(mapping):
    """
    Dirty main. Check this dirt out, it's extra dirty.
    Plots giving data.

    :param mapping: data satisfying structure generated by log_stat.py
    :return: None
    """

    title = mapping["stream_title"]
    interval = mapping["interval"]

    data = mapping["data"]
    gain_total = max(data["viewCount"]) - min(data["viewCount"])

    view_gain, fluctuation = viewer_fluctuation_data(data["viewCount"], data["concurrentViewers"])

    figure, axes = pyplot.subplots(2, 1, figsize=(16, 8))
    assert figure

    fig_manager = pyplot.get_current_fig_manager()
    fig_manager.set_window_title(f"Samples: {len(view_gain)} / "
                                 f"Duration: {len(view_gain) * interval / 60:0.2f}h / "
                                 f"Gain total: {gain_total}")

    # Plot 1
    axes[0].set_title(title, fontproperties=font)
    axes[0].plot(data["viewCount"], color='cornflowerblue', label="Total views")
    axes[0].plot(data["concurrentViewers"], color='orange', label="Live viewers")
    axes[0].plot(data["likeCount"], color='green', label="Upvote")
    axes[0].plot(data["dislikeCount"], color='red', label="Downvote")
    axes[0].set_xlabel(f"time({interval}sec unit)")
    axes[0].legend()

    # determine min-max viewers
    max_val = max(data["viewCount"])
    axes[0].set_yticks(tuple(n for n in range(0, max_val + 1, max_val // 10)))

    # Plot 2
    axes[1].plot(view_gain, color="turquoise", label="View increment")
    axes[1].plot(fluctuation, color="coral", label="Live delta")
    axes[1].legend()

    pyplot.show()


if __name__ == '__main__':
    try:
        with open(argv[-1], encoding="utf8") as fp:
            loaded_data = json.load(fp)

    except FileNotFoundError:
        print(f"File {argv[-1]} does not exist.")

    else:
        plot_main(loaded_data)
