#!/usr/bin/python

"""
Simple plot viewer for my own accumulated data.
"""

import itertools
import pathlib
import json
from array import array
from sys import argv
from typing import Tuple

from matplotlib import pyplot
from matplotlib.font_manager import FontProperties


font = FontProperties(fname=pathlib.Path("Font/NotoSansMonoCJKkr-Regular.otf"))


def viewer_fluctuation_data(total_view, concurrent_view) -> Tuple[array, array]:
    """
    Calculate possible viewer gain/lose from fluctuation of total view and live-viewers.

    :param total_view: Any sequence containing total views over time.
    :param concurrent_view: Any sequence containing live viewers over time.
    :return: int array for each approximate gain/lose of live viewers.
    """

    def view_diff_gen(source):
        yield 0

        iterator = zip(source, itertools.islice(source, 1, None))

        for previous, current in iterator:
            yield current - previous

    total_diff_gen = view_diff_gen(total_view)
    live_diff_gen = view_diff_gen(concurrent_view)

    # Total view counts goes up until unknown certain point,
    # if video was re-watched more than 30 sec during session.

    # total_dif == added number of stream viewers, total_dif - live_dif == viewers left stream
    total_diff = array("i", total_diff_gen)
    live_view_diff = array("i", (total - live for total, live in zip(total_diff, live_diff_gen)))

    live_view_gain = array("i", (n if n > 0 else 0 for n in live_view_diff))
    live_view_left = array("i", (n if n < 0 else 0 for n in live_view_diff))

    return live_view_gain, live_view_left


def plot_main(mapping):
    """
    Dirty main. Check this dirt out, it's extra dirty.
    Plots giving data.

    :param mapping: data satisfying structure generated by log_stat.py
    :return: None
    """

    title = mapping["stream_title"]
    interval = mapping["interval"]

    data = mapping["data"]
    live_gain, live_left = viewer_fluctuation_data(data["viewCount"], data["concurrentViewers"])

    live_loss_total = sum(live_left)
    live_gain_total = sum(live_gain)
    gain_total = max(data["viewCount"]) - min(data["viewCount"])

    figure, axes = pyplot.subplots(2, 1, figsize=(16, 8))
    assert figure

    pyplot.get_current_fig_manager().set_window_title(f"Gain total: {gain_total} / "
                                                      f"Live gain total: {live_gain_total} / "
                                                      f"Live loss total: {live_loss_total}")

    # Plot 1
    axes[0].set_title(title, fontproperties=font)
    axes[0].plot(data["viewCount"], color='cornflowerblue', label="Total views")
    axes[0].plot(data["concurrentViewers"], color='orange', label="Live viewers")
    axes[0].plot(data["likeCount"], color='green', label="Upvote")
    axes[0].plot(data["dislikeCount"], color='red', label="Downvote")
    axes[0].set_xlabel(f"time({interval}sec unit)")
    axes[0].legend()

    # determine min-max viewers
    max_val = max(data["viewCount"])
    axes[0].set_yticks(tuple(n for n in range(0, max_val + 1, max_val // 10)))

    # Plot 2
    axes[1].plot(live_gain, color="green", label="Viewer gain approx.")
    axes[1].plot(live_left, color="red", label="Viewer loss approx.")
    axes[1].legend()

    pyplot.show()


if __name__ == '__main__':
    try:
        with open(argv[-1], encoding="utf8") as fp:
            loaded_data = json.load(fp)

    except FileNotFoundError:
        print(f"File {argv[-1]} does not exist.")

    else:
        plot_main(loaded_data)
